# Generated by Django 2.0.1 on 2018-01-28 22:27

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone_number', models.CharField(help_text='999-999-9999', max_length=12)),
                ('address', models.TextField(blank=True, null=True)),
                ('picture', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='people_pictures')),
                ('status_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Person Type',
                'verbose_name_plural': 'Person Types',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='person_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.PersonType'),
        ),
    ]
