# Generated by Django 2.0.2 on 2018-02-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180213_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
