# Generated by Django 2.0.2 on 2018-02-22 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180222_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product', verbose_name='Product name'),
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('product', 'active')},
        ),
    ]
