# Generated by Django 2.0.2 on 2018-02-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180222_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='end_date',
            new_name='expiration_date',
        ),
    ]
