# Generated by Django 2.0.2 on 2018-02-23 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20180223_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='comment',
            new_name='product_description',
        ),
    ]
